### ISSUE TITLE
Error on MouseTest_sample - ValueError: Unknown Distance Metric: wminkowski

### ISSUE THREAD

**Issue by Vcat74** [csudre/NMJ_Analyser#1]
<img width="625" alt="Screen Shot 2022-03-13 at 5 46 43 PM" src="https://user-images.githubusercontent.com/101529080/158080619-b1ee6968-134d-417f-91e9-c9f76072ab4f.png">
Hello, I tried to use your tool because i found it really amazing and it will be very useful for our project. However, I'm a beginner in bioinformatic so I tried to follow as rigourously as possible your tutorial but after process, it return me 3 .nii.gz file (no csv) and the terminal of my mac return me an error (shown in the screenshot). Is their  way to solve this problem. It might be very very easy but I'm a beginner.  Thanks for this very interesting tool !

**Comment by haisai23** [comment]
I'm also facing a similar issue. Have you been able to solve it?

**Comment by alanmejiamaza** [comment]
Hi, were you able to fix this issue? I can help.
Thanks

**Comment by victorcat4** [comment]
Hello, yes I managed to solve it but I can't remember how ! Sorry.. I do remember that at some point my images were just too big (leading to crash of the job) and reducing their quality solved my problem

**Comment by haisai23** [comment]
Hey,  no I was not able to resolve it.

On Oct 3, 2023, at 0:15 AM, Victor Cat ***@***.***> wrote:

﻿

Hello, yes I managed to solve it but I can't remember how ! Sorry.. I do remember that at some point my images were just too big (leading to crash of the job) and reducing their quality solved my problem

**Comment by alanmejiamaza** [comment]
Hi, I can not see your email.

Please contact here: "mejia.maza.alan@gmail.com"
Thanks
